# As cf-factservice.yaml and this file are essentially identical, please reference that file for any comments

apiVersion: v1
kind: Service
metadata:
  name: cf-frontend-service
spec:
  ports:
  - name: http # This is a difference, but just tells the service to listen on HTTP (vs grpc-web)
    port: 80
  selector:
    app: cf-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cf-frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cf-frontend
    spec:
      containers:
      - name: cf-frontend
        image: cf-frontend:v1
