apiVersion: v1
kind: Service
metadata:
  name: cf-factservice
  labels:
    app: cf-factservice
spec:
  ports:
  - name: grpc-web
    port: 80
  selector:
    app: cf-factservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cf-factservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cf-factservice
        version: v1
    spec:
      containers:
      - name: cf-factservice
        image: cf-factservice:v1
        ports:
        - containerPort: 80
