# As cf-factservice.yaml and this file are essentially identical, please reference that file for any comments

apiVersion: v1
kind: Service
metadata:
  name: cf-frontend-service
spec:
  ports:
  # This slighty different from the cf-factservice, but just tells the service to listen on HTTP
  # Whereas cf-factservice depends on grpc-web, rather than HTTP
  # The default, if not specified is TCP
  - name: http 
    port: 80
  selector:
    app: cf-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cf-frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cf-frontend
    spec:
      containers:
      - name: cf-frontend
        image: cf-frontend:v1
        ports:
        - containerPort: 80
